### PR TITLE
Add Travis CI support

### PR DESCRIPTION
**Pull request by kimptoc**
Hi,

Seems I broke Travis CI by re-creating my fork :(

But it should work - honest.  

The build was broken due to my test relating to the missing attributes - nil vs exception.

The previous build worked ok for MRI.

Cheers,
Chris

### CODE REVIEW

**Comment by kimptoc** [comment]
I made a small README change to trigger a rebuild - it fails on jruby and rubinius due to ruby subtleties - but works on MRI - so I disabled the others.

**Comment by haileys** [comment]
@kimptoc Hey sorry, didn't see this PR earlier. Do you mind adding 2.0.0 to the version list? Cheers

**Comment by kimptoc** [comment]
Done :)

**Comment by kimptoc** [comment]
Thanks - although for the build pass/fail badge in the readme to work you will need to setup an account on TravisCI (its very easy :)  ) 

http://about.travis-ci.org/docs/user/getting-started/

**Pull request merged**
