### PR TITLE
Add Travis CI support

### PR DESCRIPTION
**Pull request by kimptoc**
To set this up, you need to setup a Travis account and enable this project for Travis CI, see the docs:

http://about.travis-ci.org/docs/user/getting-started/

### CODE REVIEW

**Comment by kimptoc** [comment]
As an aside  - the jruby/mri builds are failing due to ordering of hash elements - I thought ruby 1.9 preserved that ordering in some way... maybe its during iteration only...

I guess the hash compares need to be tweaked to pass - I could do that if ok with you :)

**Comment by kimptoc** [comment]
Oops - should have done a feature branch for travis - now my other test has slipped through...  let me know what you think on the missing attribute issue I have raised and I will re-do these as needed.

**Comment by haileys** [comment]
I'm open to adding Travis CI, but I'm not going to accept this PR until travis is green (on MRI at least).

If you squash your commits, that should trigger a rebuild on travis.

**Comment by kimptoc** [comment]
Will re-do the commit as this one has confused things with the test changes.

**Pull request closed without merging**
